"""empty message

Revision ID: 0916051dc3bf
Revises: f5dabe48daa6
Create Date: 2017-06-15 15:20:34.200354

"""

# revision identifiers, used by Alembic.
revision = '0916051dc3bf'
down_revision = 'f5dabe48daa6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_time', sa.String(length=255), nullable=True))
    op.drop_column('users', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_column('users', 'create_time')
    # ### end Alembic commands ###
