"""empty message

Revision ID: 1285a995a670
Revises: 9876dab3c8a1
Create Date: 2017-07-03 23:27:50.707831

"""

# revision identifiers, used by Alembic.
revision = '1285a995a670'
down_revision = '9876dab3c8a1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chess', sa.Column('chess_board', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chess', 'chess_board')
    # ### end Alembic commands ###
