"""empty message

Revision ID: 1e89535e4703
Revises: e50745144c92
Create Date: 2017-03-29 01:25:36.095377

"""

# revision identifiers, used by Alembic.
revision = '1e89535e4703'
down_revision = 'e50745144c92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_type', sa.String(length=1000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_type')
    ### end Alembic commands ###
