"""empty message

Revision ID: 22c23b1296a8
Revises: 9abcde6833df
Create Date: 2017-04-06 01:26:11.822533

"""

# revision identifiers, used by Alembic.
revision = '22c23b1296a8'
down_revision = '9abcde6833df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('zan', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'zan')
    # ### end Alembic commands ###
