"""empty message

Revision ID: 31a3569b6369
Revises: 22c23b1296a8
Create Date: 2017-04-07 01:38:26.313232

"""

# revision identifiers, used by Alembic.
revision = '31a3569b6369'
down_revision = '22c23b1296a8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'zan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('zan', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
