"""empty message

Revision ID: 390b63a723a6
Revises: a0ced531feed
Create Date: 2017-07-03 22:17:38.222709

"""

# revision identifiers, used by Alembic.
revision = '390b63a723a6'
down_revision = 'a0ced531feed'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chess', 'chess_board')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chess', sa.Column('chess_board', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
