"""empty message

Revision ID: 3a2c8293219d
Revises: bfe4acb2a304
Create Date: 2017-07-03 22:23:30.941728

"""

# revision identifiers, used by Alembic.
revision = '3a2c8293219d'
down_revision = 'bfe4acb2a304'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chess')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chess',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('room', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('chess_board', mysql.LONGTEXT(), nullable=True),
    sa.Column('created_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
