"""empty message

Revision ID: 3c7ff6dae28b
Revises: dd6bd8d02abe
Create Date: 2017-04-07 15:16:25.568214

"""

# revision identifiers, used by Alembic.
revision = '3c7ff6dae28b'
down_revision = 'dd6bd8d02abe'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zans', sa.Column('liked', sa.Integer(), nullable=True))
    op.drop_column('zans', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zans', sa.Column('status', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('zans', 'liked')
    # ### end Alembic commands ###
