"""empty message

Revision ID: 59c170d304e0
Revises: 390b63a723a6
Create Date: 2017-07-03 22:18:00.342518

"""

# revision identifiers, used by Alembic.
revision = '59c170d304e0'
down_revision = '390b63a723a6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chess', sa.Column('chess_board', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chess', 'chess_board')
    # ### end Alembic commands ###
