"""empty message

Revision ID: 776ac29611c7
Revises: 8a5b1dec9693
Create Date: 2017-03-23 17:12:43.489526

"""

# revision identifiers, used by Alembic.
revision = '776ac29611c7'
down_revision = '8a5b1dec9693'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('href', sa.String(length=1000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'href')
    ### end Alembic commands ###
