"""empty message

Revision ID: 99487c840e15
Revises: 0916051dc3bf
Create Date: 2017-06-30 21:59:48.647691

"""

# revision identifiers, used by Alembic.
revision = '99487c840e15'
down_revision = '0916051dc3bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen_at', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'online')
    op.drop_column('users', 'last_seen_at')
    # ### end Alembic commands ###
