"""empty message

Revision ID: 9abcde6833df
Revises: 1e89535e4703
Create Date: 2017-03-30 21:04:19.119923

"""

# revision identifiers, used by Alembic.
revision = '9abcde6833df'
down_revision = '1e89535e4703'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
