"""empty message

Revision ID: a0ced531feed
Revises: f49f210b80c2
Create Date: 2017-07-03 22:15:41.450746

"""

# revision identifiers, used by Alembic.
revision = 'a0ced531feed'
down_revision = 'f49f210b80c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chess', sa.Column('created_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chess', 'created_at')
    # ### end Alembic commands ###
