"""empty message

Revision ID: ad99ff79d4f4
Revises: 99487c840e15
Create Date: 2017-07-02 20:53:52.942650

"""

# revision identifiers, used by Alembic.
revision = 'ad99ff79d4f4'
down_revision = '99487c840e15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
