"""empty message

Revision ID: b71115992c0b
Revises: 9ff4efa70d4b
Create Date: 2017-04-07 11:59:21.265374

"""

# revision identifiers, used by Alembic.
revision = 'b71115992c0b'
down_revision = '9ff4efa70d4b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('zan_count', sa.Integer(), nullable=True))
    op.drop_column('comments', 'zan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('zan', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('comments', 'zan_count')
    # ### end Alembic commands ###
