"""empty message

Revision ID: c36c5d7db24b
Revises: 1285a995a670
Create Date: 2017-07-09 22:08:49.277439

"""

# revision identifiers, used by Alembic.
revision = 'c36c5d7db24b'
down_revision = '1285a995a670'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('created_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'created_at')
    # ### end Alembic commands ###
