"""empty message

Revision ID: d24b3245969f
Revises: None
Create Date: 2017-03-23 10:30:25.941898

"""

# revision identifiers, used by Alembic.
revision = 'd24b3245969f'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('checked', sa.String(length=10), nullable=True))
    op.add_column('messages', sa.Column('time', sa.BigInteger(), nullable=True))
    op.drop_column('messages', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('username', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('messages', 'time')
    op.drop_column('messages', 'checked')
    ### end Alembic commands ###
