"""empty message

Revision ID: e50745144c92
Revises: 776ac29611c7
Create Date: 2017-03-24 13:56:52.928916

"""

# revision identifiers, used by Alembic.
revision = 'e50745144c92'
down_revision = '776ac29611c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('receiver', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'receiver')
    ### end Alembic commands ###
