"""empty message

Revision ID: f0919adfe394
Revises: ad99ff79d4f4
Create Date: 2017-07-03 13:01:30.856292

"""

# revision identifiers, used by Alembic.
revision = 'f0919adfe394'
down_revision = 'ad99ff79d4f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('match_password', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('ready', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'ready')
    op.drop_column('rooms', 'match_password')
    # ### end Alembic commands ###
