"""empty message

Revision ID: f49f210b80c2
Revises: f0919adfe394
Create Date: 2017-07-03 21:46:32.187697

"""

# revision identifiers, used by Alembic.
revision = 'f49f210b80c2'
down_revision = 'f0919adfe394'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chess', ['room'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chess', type_='unique')
    # ### end Alembic commands ###
