"""empty message

Revision ID: f5dabe48daa6
Revises: 3c7ff6dae28b
Create Date: 2017-05-12 18:54:09.753462

"""

# revision identifiers, used by Alembic.
revision = 'f5dabe48daa6'
down_revision = '3c7ff6dae28b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('time', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time')
    # ### end Alembic commands ###
